SET IDENTITY_INSERT [dbo].[Articulos] ON

INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (1, 500, '1234567891231', N'Pack Hojas de tamaño A4', N'Hoja A4')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (2, 50, '9876543210981', N'Tijeras escolares', N'Tijeras')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (3, 90, '4561237894561', N'Cuadernos de 100 hojas', N'Cuaderno')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (4, 30, '7891234567891', N'Lápices HB', N'Lápiz HB')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (5, 1000, '3216549871231', N'Mochilas escolares', N'Mochila')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (6, 25, '6549873214561', N'Gomas de borrar', N'Goma de borrar')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (7, 200, '7894561237819', N'Calculadoras científicas', N'Calculadora')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (8, 23, '1237896543121', N'Cartulinas de colores', N'Cartulina')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (9, 15, '4567891231987', N'Pegamento en barra', N'Pegamento')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (10, 30, '1122334451566', N'Bolígrafos azules', N'Bolígrafo')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (11, 28, '2233445516677', N'Resaltadores', N'Resaltador')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (12, 60, '3344556617788', N'Libretas de notas', N'Libreta')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (13, 150, '4455667718899', N'Grampas para engrapadora', N'Grampas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (14, 17, '5566778891900', N'Notas adhesivas', N'Post-it')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (15, 40, '6677889902011', N'Cinta adhesiva', N'Cinta Adhesiva')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (16, 45, '7788991012122', N'Regla 30 cm', N'Regla')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (17, 35, '8899101213233', N'Sacapuntas', N'Sacapuntas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (18, 12, '9901012324344', N'Carpeta tamaño carta', N'Carpeta')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (19, 55, '1011123435455', N'Papel para impresora', N'Papel Impresora')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (20, 65, '1112234546566', N'Archivador de documentos', N'Archivador')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (21, 18, '1213345657677', N'Marcadores permanentes', N'Marcador Permanente')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (22, 20, '1314456768788', N'Plastilina', N'Plastilina')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (23, 27, '1415567879899', N'Borrador para pizarra', N'Borrador Pizarra')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (24, 32, '1516678980900', N'Lapiceros de colores', N'Lapiceros')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (25, 22, '1617789091011', N'Pegamento líquido', N'Pegamento Líquido')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (26, 30, '1718899102122', N'Subrayadores', N'Subrayador')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (27, 25, '1819901213233', N'Temperas', N'Tempera')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (28, 70, '1921012324344', N'Compás de precisión', N'Compás')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (29, 35, '2021123435455', N'Sacagrapas', N'Sacagrapas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (30, 45, '2122234546566', N'Taladro de papel', N'Taladro Papel')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (31, 15, '2223345657677', N'Corrector líquido', N'Corrector Líquido')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (32, 28, '2324456768788', N'Pintura acrílica', N'Pintura Acrílica')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (33, 50, '2425567879899', N'Sellador de documentos', N'Sellador')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (34, 12, '2526678980900', N'Pinzas para papel', N'Pinzas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (35, 75, '2627789091011', N'Stencil de letras', N'Stencil')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (36, 40, '2728899102122', N'Tinta para sellos', N'Tinta Sellos')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (37, 65, '2829901213233', N'Brochas para pintar', N'Brochas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (38, 25, '2931012324344', N'Cúter de precisión', N'Cúter')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (39, 80, '3031123435455', N'Ceras para colorear', N'Ceras')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (40, 18, '3132234546566', N'Tarjetas de presentación', N'Tarjetas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (41, 22, '3233345657677', N'Chinchetas', N'Chinchetas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (42, 27, '3334456768788', N'Grapadoras', N'Grapadora')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (43, 12, '3435567879899', N'Clips para papel', N'Clips')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (44, 55, '3536678980900', N'Cajas organizadoras', N'Caja Organizadora')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (45, 37, '3637789091011', N'Fólderes colgantes', N'Fólder Colgante')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (46, 43, '3738899102122', N'Reloj de pared', N'Reloj Pared')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (47, 60, '3839901213233', N'Globo terráqueo', N'Globo Terráqueo')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (48, 22, '3941012324344', N'Pinzas de presión', N'Pinza de Presión')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (49, 28, '4041123435455', N'Tiras adhesivas', N'Tira Adhesiva')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (50, 19, '4142234546566', N'Marcadores de pizarra', N'Marcador Pizarra')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (51, 38, '4243345657677', N'Pinceles de acuarela', N'Pinceles')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (52, 34, '4344456768788', N'Borradores de tinta', N'Borrador Tinta')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (53, 48, '4445567879899', N'Tabletas de notas', N'Tableta de Notas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (54, 52, '4546678980900', N'Cinta métrica', N'Cinta Métrica')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (55, 63, '4647789091011', N'Manualidades de papel', N'Manualidades')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (56, 41, '4748899102122', N'Tablero de corcho', N'Tablero de Corcho')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (57, 29, '4849901213233', N'Transportador', N'Transportador')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (58, 44, '4951012324344', N'Papel celofán', N'Papel Celofán')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (59, 55, '5051123435455', N'Escuadra', N'Escuadra')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (60, 17, '5152234546566', N'Sujetapapeles', N'Sujetapapeles')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (61, 68, '5253345657677', N'Bolígrafos de colores', N'Bolígrafos Colores')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (62, 32, '5354456768788', N'Grapas de colores', N'Grapas Colores')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (63, 57, '5455567879899', N'Calendario de escritorio', N'Calendario Escritorio')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (64, 39, '5556678980900', N'Tizas de colores', N'Tizas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (65, 26, '5657789091011', N'Cuadernos de dibujo', N'Cuaderno Dibujo')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (66, 49, '5758899102122', N'Tijeras de precisión', N'Tijera Precisión')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (67, 24, '5859901213233', N'Rotuladores permanentes', N'Rotulador Permanente')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (68, 72, '5961012324344', N'Temperas escolares', N'Tempera Escolar')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (69, 53, '6061123435455', N'Tablero magnético', N'Tablero Magnético')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (70, 36, '6162234546566', N'Caja de herramientas', N'Caja Herramientas')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (71, 43, '6263345657677', N'Tabla de cortar', N'Tabla Cortar')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (72, 39, '6364456768788', N'Papel adhesivo', N'Papel Adhesivo')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (73, 61, '6465567879899', N'Lapiceros automáticos', N'Lapicero Automático')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (74, 54, '6566678980900', N'Tizas líquidas', N'Tiza Líquida')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (75, 48, '6667789091011', N'Pizarras blancas', N'Pizarra Blanca')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (76, 25, '6768899102122', N'Imanes para pizarra', N'Imán Pizarra')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (77, 33, '6869901213233', N'Tintas para pluma', N'Tinta Pluma')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (78, 28, '6971012324344', N'Ceras blandas', N'Cera Blanda')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (79, 22, '7071123435455', N'Ceras duras', N'Cera Dura')
INSERT [dbo].[Articulos] ([Id], [PrecioVP], [CodigoProveedor_codigo], [Descripcion_Descripcion], [NombreArticulo_Nombre]) VALUES (80, 30, '7172234546566', N'Lapiceros borrables', N'Lapicero Borrable')

SET IDENTITY_INSERT [dbo].[Articulos] OFF
